import clusters

blognames,words,data=clusters.readfile('blogsdata.txt') 
kclust=clusters.kcluster(data,k=20)
print([blognames[r] for r in kclust[0]])
print([blognames[r] for r in kclust[1]])
print([blognames[r] for r in kclust[2]])
print([blognames[r] for r in kclust[3]])
print([blognames[r] for r in kclust[4]])
print([blognames[r] for r in kclust[5]])
print([blognames[r] for r in kclust[6]])
print([blognames[r] for r in kclust[7]])
print([blognames[r] for r in kclust[8]])
print([blognames[r] for r in kclust[9]])
print([blognames[r] for r in kclust[10]])
print([blognames[r] for r in kclust[11]])
print([blognames[r] for r in kclust[12]])
print([blognames[r] for r in kclust[13]])
print([blognames[r] for r in kclust[14]])
print([blognames[r] for r in kclust[15]])
print([blognames[r] for r in kclust[16]])
print([blognames[r] for r in kclust[17]])
print([blognames[r] for r in kclust[18]])
print([blognames[r] for r in kclust[19]])
